spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test_project_4sp_db
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver

#  flyway:
#    baselineOnMigrate: true
